spring:
  application:
    name: proxy
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://localhost:8086
              predicates:
                - Path=/authentication-service/**
              filters:
                - StripPrefix=1
            - id: cv-service
              uri: http://localhost:8082
              predicates:
                - Path=/cv-service/**
              filters:
                - StripPrefix=1
            - id: entretien-service
              uri: http://localhost:8083
              predicates:
                - Path=/entretien-service/**
              filters:
                - StripPrefix=1
            - id: competence-service
              uri: http://localhost:8084
              predicates:
                - Path=/competence-service/**
              filters:
                - StripPrefix=1

            - id: offreemploi-service
              uri: http://localhost:8085
              predicates:
                - Path=/offreemploi-service/**
              filters:
                - StripPrefix=1

            - id: candidature-service
              uri: http://localhost:8087
              predicates:
                - Path=/candidature-service/**
              filters:
                - StripPrefix=1


    config:
      import-check:
        enabled: false
  config:
    import: configserver:http://localhost:8888

server:
  port: 8088

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
